/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tony_fastdfsuploader_jni_FastDFSUploader */

#ifndef _Included_com_tony_fastdfsuploader_jni_FastDFSUploader
#define _Included_com_tony_fastdfsuploader_jni_FastDFSUploader

#include <android/log.h>
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO, "(>_<)", format, ##__VA_ARGS__)


#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_tony_fastdfsuploader_jni_FastDFSUploader
 * Method:    upload
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tony_fastdfsuploader_jni_FastDFSUploader_upload
  (JNIEnv *env, jclass clazz, jstring jstr) {


    uploadProgress(0.1);

    uploadProgress(0.3);

    uploadProgress(1.0);

    return 1;
  }

/*
 * 回调主线程中的方法
 * Class:     com_tony_fastdfsuploader_activity_MainActivity
 * Method:    uploadProgress
 * Signature: (F)V
 */
void uploadProgress(JNIEnv *env, jobject obj, float progress) {

    static jclass clazz = (*env)->FindClass(env, "com/tony/fastdfsuploader/activity/MainActivity");

    if(clazz == 0) {
        LOGI("find not class");
        return;
    }

    static jmethodID methodID = (*env)->GetMethodID(env, clazz, "uploadProgress", "(F)V");

    if (methodID == 0) {
        LOGI("find not method");
        return;
    }

    LOGI("exec successful.");
    (*env)->CallVoidMethod(env, obj, methodID);
}


#ifdef __cplusplus
}
#endif
#endif
