/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_tony_fastdfsuploader_jni_FastDFSUploader */

#ifndef _Included_com_tony_fastdfsuploader_jni_FastDFSUploader
#define _Included_com_tony_fastdfsuploader_jni_FastDFSUploader

#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <malloc.h>

#include <android/log.h>

#define LOG_TAG "System.out"
#define LOGI(format, ...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, format, ##__VA_ARGS__)


#ifdef __cplusplus
extern "C" {
#endif

JNIEnv * g_env = NULL;

void uploadProgress(JNIEnv *env, jobject obj, jfloat progress);


char* Jstring2CStr(JNIEnv* env, jstring jstr) {
	char* rtn = NULL;
	jclass clsstring = (*env)->FindClass(env, "java/lang/String");
	jstring strencode = (*env)->NewStringUTF(env, "UTF-8");
	jmethodID mid = (*env)->GetMethodID(env, clsstring, "getBytes",
			"(Ljava/lang/String;)[B");
	jbyteArray barr = (jbyteArray) (*env)->CallObjectMethod(env, jstr, mid,
			strencode); // String .getByte("GB2312");
	jsize alen = (*env)->GetArrayLength(env, barr);
	jbyte* ba = (*env)->GetByteArrayElements(env, barr, JNI_FALSE);
	if (alen > 0) {
		rtn = (char*) malloc(alen + 1); //"\0"
		memcpy(rtn, ba, alen);
		rtn[alen] = 0;
	}
	//rtn是动态内存分配---将ba指针的内容拷贝到rtn中,所以后面需要释放的是ba指针
	(*env)->ReleaseByteArrayElements(env, barr, rtn, 0); //
	return rtn;
}

/*
 * Class:     com_tony_fastdfsuploader_jni_FastDFSUploader
 * Method:    upload
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tony_fastdfsuploader_activity_MainActivity_upload
  (JNIEnv *env, jobject obj, jstring jstr) {

    char * path = Jstring2CStr(env, jstr);
    LOGI("upload path: %s", path);

    uploadProgress(env, obj, 0.1);

    uploadProgress(env, obj, 0.3);

    uploadProgress(env, obj, 1.0);

    return 1;
  }

/*
 * 回调主线程中的方法
 * Class:     com_tony_fastdfsuploader_activity_MainActivity
 * Method:    setUploadProgress
 * Signature: (F)V
 */
void uploadProgress(JNIEnv *env, jobject obj, jfloat progress) {

    jclass clazz = (*env)->FindClass(env, "com/tony/fastdfsuploader/activity/MainActivity");

    if(clazz == 0) {
        LOGI("find not class");
        return;
    }

    jmethodID methodID = (*env)->GetMethodID(env, clazz, "setUploadProgress", "(F)V");

    if (methodID == 0) {
        LOGI("find not method");
        return;
    }

    LOGI("exec successful.");
    (*env)->CallVoidMethod(env, obj, methodID, progress);
}


#ifdef __cplusplus
}
#endif
#endif
